config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    authenticated :user do
      root 'projects#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :projects do
    resources :project_tasks
  end
  resources :project_tasks

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :project_tasks
  has_many :users, through: :project_tasks

  def get_all_task
  	self.project_tasks
  end

  
end

app/models/project_task.rb
class ProjectTask < ActiveRecord::Base
  belongs_to :project
  belongs_to :user

  def get_developer_email
  	User.find_by_id(self.user_id).email rescue ""
  end

  def self.get_all_task(projects,user)
  	if user.role == "developer"
  	  return ProjectTask.where(:user_id => user.id)
    elsif user.role == "admin"
      return projects.project_tasks
    else
    	return []
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :projects
  has_many :projects, through: :project_tasks
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    if current_user.role == "developer"
      project_tasks_path 
    else
      projects_path
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/project_tasks_controller.rb
class ProjectTasksController < ApplicationController
  before_action :authenticate_user!
  before_action :find_project
  
  def index

    @project_tasks = ProjectTask.get_all_task(@project,current_user)
  end

  def new
    @project_task = @project.project_tasks.new    
  	@users = User.where(:role => "Developer")
  end

  def create
    @project_task = @project.project_tasks.new(project_task_params)
    if @project_task.save
      redirect_to project_project_tasks_path
    else
      render :new
    end
  end

  def edit
  	@project_task = @project.project_tasks.find_by_id(params[:id])
  	@users = User.where(:role => "Developer")
  end

  def update
  	@project_task = @project.project_tasks.find_by_id(params[:id])
    if @project_task.update(project_task_params)
      if project_task_params[:status].present?
        redirect_to project_tasks_path
      else
        redirect_to project_project_tasks_path
      end
    else
      render :edit
    end
  end

  def destroy
  	
  end

  protected
    
  def project_task_params
    params[:project_task].permit!
  end

  def find_project
  	@project = Project.find_by_id(params[:project_id])
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  def index
    @projects = Project.all
  end

  def new
    @project = Project.new    
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to projects_path
    else
      render :new
    end
  end

  protected
    
  def project_params
    params[:project].permit!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/project_tasks_helper.rb
module ProjectTasksHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/home/index.html.erb
<% if user_signed_in? %>

<h3>you have succesfully signed in</h3>
<%= link_to "Sign Out", destroy_user_session_path, :method => :delete %>

<% else %>

<h1> welcom to rails community</h1>
<%= link_to "Sign In", new_user_session_path, :method => :get %>
<%= link_to "Sign up", new_user_registration_path, :method => :get %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Assignment</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <div class="col-md-10"></div>
      <div class="col-md-2">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to "Sign Out", destroy_user_session_path, :method => :delete if current_user %>
        </li>
      </ul>
      </div>
    </div>
  </div>
</nav>
<div class="container">
  <div class="row">
    <%= yield %>
  </div>
</div>
<style>
body {
padding-top: 70px;
/* Required padding for .navbar-fixed-top. Remove if using .navbar-static-top. Change if height of navigation changes. */
}
</style>
</body>
</html>

app/views/project_tasks/edit.html.erb
<%= form_for [@project,@project_task] do |form| %>
  <p>
    <%= form.label :name, "Project Task Name:" %>
    <%= form.text_field :name %>
  </p>
  
  <p>
    <%= form.label :user_id, "Assign Developer:" %>
    <%= form.select :user_id, @users.pluck(:email,:id)%>
  </p>

  <% if @project_task.errors[:name].any? %>
    <p class='error-messages'>
      The given url <%= @project_task.errors[:name].to_sentence %>.
    </p>
  <% end %>

  <p class='buttons'>
    <%= form.submit "Save" %>
  </p>

<% end %>

app/views/project_tasks/index.html.erb
<% if current_user.role == "admin" %>
  <ul class="nav navbar-nav">
    <li>
      <%= link_to "Create Project Task", new_project_project_task_path(project_id: params[:project_id]) %>
    </li>
  </ul>
  <% @project_tasks.each_with_index do |project_task, index| %>
     <%= label :name, "Project Tasks Name:" %>
     <%= project_task.name %>
     <%= link_to "Edit Task", edit_project_project_task_path(:project_id => @project.id, :id => project_task)  %>
     </br>
  <% end %>
  <table class="table">
    <thead>
      <tr>
        <th>#</th>
        <th>Project Tasks Name</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @project_tasks.each_with_index do |project_task, index| %>
        <tr>
          <th scope="row"><%= index + 1 %></th>
          <td><%= project_task.name %></td>
          <td>
            <%= link_to "Edit Task", edit_project_project_task_path(:project_id => @project.id, :id => project_task)  %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% elsif %>
  <table class="table">
    <thead>
      <tr>
        <th>#</th>
        <th>Status</th>
        <th>Name</th>
        <th>Change Status</th>
      </tr>
    </thead>
    <tbody>
      <% @project_tasks.each_with_index do |task, index| %>
        <tr>
          <th scope="row"><%= index + 1 %></th>
          <td><%= task.status %></td>
          <td><%= task.name %></td>
          <td>
            <% if task.status.downcase == "new" %>
              <%= link_to "In Progress", project_project_task_path(:project_id => task.project_id, :id => task.id, :project_task => {:status => "in progress" }), :method => "put" %> 
            <% elsif task.status.downcase == "in progress" %>
              <%= link_to "Done",  project_project_task_path(:project_id => task.project_id, :id => task.id, :project_task => {:status => "done" }), :method => "put" %>
            <% elsif task.status.downcase == "done" %>
              <%= link_to "In Progress",  project_project_task_path(:project_id => task.project_id, :id => task.id, :project_task => {:status => "in progress"}), :method => "put" %>
            <% end %>  
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/project_tasks/new.html.erb
<%= form_for [@project,@project_task] do |form| %>
  <p>
    <%= form.label :name, "Project Task Name:" %>
    <%= form.text_field :name %>
  </p>
  <p>
    <%= form.label :user_id, "Assign Developer:" %>
    <%= form.select :user_id, @users.pluck(:email,:id), :prompt => "Select The Developer"%>
  </p>

  <% if @project_task.errors[:name].any? %>
    <p class='error-messages'>
      The given url <%= @project_task.errors[:name].to_sentence %>.
    </p>
  <% end %>

  <p class='buttons'>
    <%= form.submit "Save" %>
  </p>

<% end %>

app/views/projects/index.html.erb
<% if user_signed_in? %>
  <div class="row">
  <div class="col-md-10"></div>
  <div class="col-md-1">
    <%= link_to "Create Project",  new_project_path, class: "btn btn-primary" %>
  </div>
  </div>
  <div class="row">
    <% @projects.each do |project| %>
      <div class="col-sm-1" >
        <h4><span class="label label-default">Project Name</span></h4>
      </div>
      <div class="col-sm-9" style="padding-left:25px">
        <h4><%= project.name %></h4>
      </div>
      <div class="col-sm-2">
        <%= link_to "Create Task",  new_project_project_task_path(:project_id => project.id), class: "btn btn-primary" %>
      </div>

      
      <% if project.get_all_task.present? %>
        <table class="table">
          <thead>
            <tr>
              <th>#</th>
              <th>Status</th>
              <th>Name</th>
              <th>Developer</th>
              <th>Edit</th>
            </tr>
          </thead>
          <tbody>
            <% project.get_all_task.each_with_index do |task, index| %>
              <tr>
                <th scope="row"><%= index + 1 %></th>
                <td><%= task.status %></td>
                <td><%= task.name %></td>
                <td><%= task.get_developer_email %></td>
                <td>
                  <%= link_to "Edit",  edit_project_project_task_path(:project_id => project.id, :id => task.id)  %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% end %>
    <% end %>
  <% end %>
</div>

<% if false %>
  <% if user_signed_in? %>
    <%= link_to "Sign Out", destroy_user_session_path, :method => :delete %>
    <%= link_to "Create Project",  new_project_path %>
    </br>

    <% @projects.each do |project| %>
      <%= label :name, "Project Name:" %>
      <%= project.name %>
      <%= link_to "Create Task",  new_project_project_task_path(:project_id => project.id)  %> 
      </br>
      <% if project.get_all_task.present? %>
        <table>
          <tr>
            <th>Status</th>
            <th>Name</th>
            <th>Developer</th>
            <th>Edit</th>
          </tr>
          <% project.get_all_task.each do |task| %>
            <tr>
              <td><%= task.status %></td>
              <td><%= task.name %></td>
              <td><%= task.get_developer_email %></td>
              <td><%= link_to "Edit",  edit_project_project_task_path(:project_id => project.id, :id => task.id)  %></td>
            </tr>
          <% end %>
        </table>
      <% end %>  
    <% end %>

  <% else %>

    <h1> welcom to rails community</h1>
    <%= link_to "Sign In", new_user_session_path, :method => :get %>
    <%= link_to "Sign up", new_user_registration_path, :method => :get %>

  <% end %>
<% end %>

app/views/projects/new.html.erb
<%= form_for @project do |form| %>
  <p>
    <%= form.label :name, "Project Name:" %>
    <%= form.text_field :name %>
  </p>

  <% if @project.errors[:name].any? %>
    <p class='error-messages'>
      The given url <%= @project.errors[:name].to_sentence %>.
    </p>
  <% end %>

  <p class='buttons'>
    <%= form.submit "Save" %>
  </p>

<% end %>